name: Frontend deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - shell: bash
        env:
          REGISTRY_ADDR: ${{ secrets.REGISTRY_ADDR }}
          RUNNER_ALLOW_RUNASROOT: '1'
        run: |
          printf '{ "insecure-registries": [ "%s" ] }' $REGISTRY_ADDR > $PWD/daemon.json
          sudo cp $PWD/daemon.json /etc/docker/daemon.json
          sudo systemctl restart docker
          cd web
          docker build -t $REGISTRY_ADDR/frontend:1.2 .
          docker push $REGISTRY_ADDR/frontend:1.2
